package com.abdullahkahraman.exchange.enums;

public enum ErrorCode {
    CSV_FORMAT_ERROR,
    VALIDATION_ERROR,
    EXTERNAL_API_FAILURE,
    TRANSACTION_NOT_FOUND,
    RATE_NOT_FOUND,
    CONVERSION_NOT_FOUND,
    INVALID_CURRENCY,
    MISSING_SEARCH_CRITERIA,
    EXCEL_FORMAT_ERROR
}
